language: swift
osx_image: xcode11.3
env:
  global:
  - FRAMEWORK_NAME=AWSAppSync
xcode_workspace: AWSAppSyncClient.xcworkspace
xcode_scheme: AWSAppSync
before_install:
- openssl aes-256-cbc -K $encrypted_6919a533707f_key -iv $encrypted_6919a533707f_iv
  -in AWSAppSyncIntegrationTests/appsync_test_credentials.json.enc
  -out AWSAppSyncIntegrationTests/appsync_test_credentials.json
  -d
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install cocoapods -v '1.8.4'
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
script:
- xcodebuild -quiet -workspace AWSAppSyncClient.xcworkspace -scheme AWSAppSync build test -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest'
deploy:
- provider: releases
  api_key:
    secure: "vYTABQb2THZA+BzuW0d01+NAY65KfYfPtDa765NtyOoBV0xORR/JAGtaC2g3FjwdpanrqDaiIAMBf2Ml+AEwxBF1UHotyiVzHc3Q0zMhocCkoqFaMwvukpW4MlC/FArvLNctTPebzKcDLROWYYu3/Ik0V8nVsMdMtexsCW0vxqomBwdcSUe6nEcvi80qhIJpZYfvVLftEn7DKb/MLGPIAhxZgqJSnHHcQFzozIrEgvP/lcYfPnj03/szFdOxW3ItjdkdrQD5peg9fi7N6uFJ5WsQaVToqGDAW9yzHaSWL558RKLKcPBzC82U3O5HP4mic6or7tSKohZEYrAHMZl2TmSwsSnL7LzSVrdOfPIg2ycGTjwbfhnf/ML36jjdLcNJnKGtRX84nnCy/v1L5giWr5m74FrpUq0p7noB+n8dyYJnBgjdqQgMdAZnpbAO9B/wWYxxRUHh3hl7hSs/UdoWiVkCnJlKERhJLfm4dBVP/tKqFmZXLCqJu1kwIc27ziX75ziPwEyBWKJfIHZuaUGxjwoPVFp0m9X0ixu8IDnFhi/c8WAqWCYWlhn9kF5BaPyXiU+o6DucKm37niRGTcSvCuJOXRi947LociX+GPv2MpFv5Xi80jv3y9BMsbc+PAu3nmY8jPVdLrb/WPczHtAMYITHYgpajF0hY0Vg6zBAl7g="
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
   repo: awslabs/aws-mobile-appsync-sdk-ios
   tags: true
- provider: script
  script: bash cocoapods_release.sh
  on:
    repo: awslabs/aws-mobile-appsync-sdk-ios
    tags: true
